[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

[dependencies]
# you can check the latest version here: https://crates.io/crates/yew
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew.git" }
yewdux = { git = "https://github.com/nmlt/yewdux.git", branch = "patch-1" }
yewdux-input = { git = "https://github.com/nmlt/yewdux.git", branch = "patch-1" }
chrono = "0.4" # For Datetime in Commit
serde = "1"
serde_json = "1"
gloo-net = "0.2"
wasm-bindgen-futures = "0.4"
gloo-console = "0.2.3"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = ["HtmlSelectElement", "HtmlOptionElement", "HtmlInputElement"]
